#!/bin/bash
# auto-memory.sh — Stop hook for session memory persistence
# Called by Claude Code Stop hook with JSON on stdin
# Saves session summary to ~/.claude/memory/sessions.md

set -e

MEMORY_DIR="$HOME/.claude/memory"
SESSIONS_FILE="$MEMORY_DIR/sessions.md"

# Ensure memory directory exists
mkdir -p "$MEMORY_DIR"

# Read hook input from stdin (JSON)
INPUT=$(cat -)

# Extract session info
TIMESTAMP=$(date '+%Y-%m-%d %H:%M:%S')
PROJECT=$(basename "$(pwd)" 2>/dev/null || echo "unknown")
BRANCH=$(git branch --show-current 2>/dev/null || echo "N/A")

# Create sessions file header if it doesn't exist
if [ ! -f "$SESSIONS_FILE" ]; then
    cat > "$SESSIONS_FILE" << 'EOF'
# Claude Code Session Log

Auto-generated by 2111framework auto-memory hook.
Each entry records when a session ended and in which project/branch.

---

EOF
fi

# Append session entry
cat >> "$SESSIONS_FILE" << EOF
### $TIMESTAMP
- **Project:** $PROJECT
- **Branch:** $BRANCH
- **Status:** Session ended

EOF

# If PROJECT_MEMORY.md doesn't exist, create a minimal template
if [ ! -f "PROJECT_MEMORY.md" ]; then
    cat > "PROJECT_MEMORY.md" << 'PMEOF'
# Project Memory

> Auto-created by 2111framework. Update with key decisions, resolved bugs, and patterns.
> Claude reads this file at session start and after /compact.

## Architecture Decisions

## Resolved Bugs

## API Limitations

## Anti-patterns

PMEOF
fi
